### PR TITLE
Goalkeeper behaviour 

### PR DESCRIPTION
**Pull request by gribes02**
- Has the same behaviour as the reciever of ball passing. However this time it is stuck on a vertical line. For now that line is the x pos of the goalkeeper however it would be nice to make the value static so that it doesn't deviate perhaps.

### CODE REVIEW

**Comment by ivrolan** [comment]
@mablin7 check the commit of the CircularPID,  could be useful to add it to the rest of the repo even if this branch needs a bit to get merged

**Comment by knyazer** [comment]
@mablin7 review please

**Review by mablin7 — APPROVED** [review]
lgtm

**Comment by knyazer** [comment]
sorry for missing stuff :(

**Comment by knyazer** [comment]
Tho... Why do you use the default PartialEq instead of mine? I don't think using the default one is correct: if angles are -pi+eps and pi-eps, they are equal..

**Comment by mablin7** [comment]
Oh sorry, I reverted the file by mistake. I added it back on main. Thanks for catching that!

**Pull request merged**
